config/routes.rb
Rails.application.routes.draw do
  resources :gardens do
    resources :plants, only: [:create, :destroy]
    
  end

  resources :plants, only: [] do
    resources :plant_tags, only: [ :new, :create ]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord

    has_many :plants, dependent: :destroy
    
    validates :name, presence: true, uniqueness: true 
    validates :banner_url, presence: true
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden

  has_many :plant_tags, dependent: :destroy
  has_many :tags, through: :plant_tags
end

app/models/plant_tag.rb
class PlantTag < ApplicationRecord
  belongs_to :plant
  belongs_to :tag

  validates :tag, uniqueness: {scope: :plant, message: "already added"}
end

app/models/tag.rb
class Tag < ApplicationRecord

    has_many :plant_tags, dependent: :destroy
    has_many :plants, through: :plant_tags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: [:show, :edit, :update, :destroy]

  # GET /gardens
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1
  def show
    @plant = Plant.new
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens
  def create
    @garden = Garden.new(garden_params)

    if @garden.save
      redirect_to @garden, notice: 'Garden was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gardens/1
  def update
    if @garden.update(garden_params)
      redirect_to @garden, notice: 'Garden was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gardens/1
  def destroy
    @garden.destroy
    redirect_to gardens_url, notice: 'Garden was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden
      @garden = Garden.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def garden_params
      params.require(:garden).permit(:name, :banner_url)
    end
end

app/controllers/plant_tags_controller.rb
class PlantTagsController < ApplicationController

    def new
       @plant = Plant.find(params[:plant_id]) 
       @plant_tag = PlantTag.new 
    end

    def create
        @plant = Plant.find(params[:plant_id]) 
        
        # @plant_tag = PlantTag.new(tag_id: params[:plant_tag][:tag]) 
        
        # @plant_tag.plant = @plant

        @tags = Tag.where(id: params[:plant_tag][:tag])
        
        @tags.each do |tag|
          plant_tag = PlantTag.new(plant: @plant, tag: tag)
          plant_tag.save
        end
        
        redirect_to garden_path(@plant.garden)
        

        # if @plant_tag.save
        #     redirect_to garden_path(@plant.garden)
        # else
        #     render :new
        # end
    end    
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController

    def create
        @plant = Plant.new(plant_params)
        @garden = Garden.find(params[:garden_id])
        @plant.garden = @garden
        if @plant.save
            redirect_to garden_path(@garden)
        else
            render :show
        end
    end

    def destroy
        @plant = Plant.find(params[:id])
        @garden = Garden.find(params[:garden_id])
        @plant.destroy

        redirect_to garden_path(@garden)
    end

    private

    def plant_params
        params.require(:plant).permit(:name, :image_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plant_tags_helper.rb
module PlantTagsHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/_form.html.erb
<%= simple_form_for(@garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gardens/edit.html.erb
<h1>Editing Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Show', @garden %> |
<%= link_to 'Back', gardens_path %>

app/views/gardens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gardens</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Banner url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gardens.each do |garden| %>
      <tr>
        <td><%= garden.name %></td>
        <td><%= garden.banner_url %></td>
        <td><%= link_to 'Show', garden %></td>
        <td><%= link_to 'Edit', edit_garden_path(garden) %></td>
        <td><%= link_to 'Destroy', garden, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Garden', new_garden_path %>

app/views/gardens/new.html.erb
<h1>New Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Back', gardens_path %>

app/views/gardens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @garden.name %>
</p>



<div class="">
  <img src="<%= @garden.banner_url %>" alt="" class="m-auto w-50 d-flex justify-content-center">

    <div class="text-center my-4">
      <%= link_to 'Edit', edit_garden_path(@garden) %> |
      <%= link_to 'Back', gardens_path %>
    </div>
</div>


<div class="m-auto w-50">
  <%= simple_form_for [@garden, @plant] do |f| %>
    <%= f.input :name %>
    <%= f.input :image_url %>
    <%= f.submit %>
  <% end %>
</div>

<div class="text-center d-flex justify-content-center p-3">
  <% @garden.plants.each do |plant| %>
    <div class="p-3 bg bg-light ml-1">
      <img src="<%= plant.image_url %>" alt="" style="width: 200px;">
      <h3><%= plant.name %></h3>
      <div class="card-tags">
        <% plant.tags.each do |tag| %>
          <span><%= tag.name %></span>
        <% end %>
        <%= link_to "+", new_plant_plant_tag_path(plant) %>
      </div>
      <div><%= link_to "Add Tag", new_plant_plant_tag_path(plant) %></div>
      <div><%= link_to "Delete", garden_plant_path(garden_id: @garden.id, id: plant.id ), method: :delete, data: {confirm: "Are you sure you want to kill me??????"} %></div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardensAndPlants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plant_tags/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <h1>Add new tag for <%= @plant.name %></h1>

      <%= simple_form_for [@plant, @plant_tag] do |f| %>
        <%#= f.input :tag, collection: Tag.all %>
        <%= f.input :tag, collection: Tag.all, input_html: {multiple: true, class: "multiple-select"}, include_hidden: false %>
        <%= f.submit "Add tag", class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>